#include <pulse/channelmap.h>
#include <pulse/context.h>
#include <pulse/def.h>
#include <pulse/direction.h>
#include <pulse/error.h>
#include <pulse/ext-device-manager.h>
#include <pulse/ext-device-restore.h>
#include <pulse/ext-stream-restore.h>
#include <pulse/format.h>
#include <pulse/gccmacro.h>
#include <pulse/glib-mainloop.h>
#include <pulse/introspect.h>
#include <pulse/mainloop-api.h>
#include <pulse/mainloop-signal.h>
#include <pulse/mainloop.h>
#include <pulse/operation.h>
#include <pulse/proplist.h>
#include <pulse/pulseaudio.h>
#include <pulse/rtclock.h>
#include <pulse/sample.h>
#include <pulse/scache.h>
#include <pulse/simple.h>
#include <pulse/stream.h>
#include <pulse/subscribe.h>
#include <pulse/thread-mainloop.h>
#include <pulse/timeval.h>
#include <pulse/utf8.h>
#include <pulse/util.h>
#include <pulse/version.h>
#include <pulse/volume.h>
#include <pulse/xmalloc.h>
